version: "3.9"
services:
  postgres:
    image: postgres:16-alpine
    container_name: atlas-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: atlas
      POSTGRES_PASSWORD: atlas
      POSTGRES_DB: atlas
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U atlas -d atlas"]
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  postgres-data:


